image:
  repository: mattermost/focalboard
  tag: 7.10.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: focalboard.seudominio.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  storageClass: managed-premium
  accessMode: ReadWriteOnce
  size: 5Gi
