apiVersion: v1
kind: ConfigMap
metadata:
  name: focalboard-config
  labels:
    app: focalboard
data:
  config.json: |
    {
      "serverRoot": "http://localhost:8000",
      "port": 8000,
      "dbtype": "sqlite3",
      "dbconfig": "./focalboard.db",
      "postgres_dbconfig": "dbname=focalboard sslmode=disable",
      "useSSL": false,
      "webpath": "./pack",
      "filespath": "./files",
      "telemetry": true,
      "prometheusaddress": ":9092",
      "session_expire_time": 2592000,
      "session_refresh_time": 18000,
      "localonly": false,
      "enableLocalMode": true,
      "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
    }