apiVersion: apps/v1
kind: Deployment
metadata:
  name: focalboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focalboard
  template:
    metadata:
      labels:
        app: focalboard
    spec:
      initContainers:
        - name: init-db
          image: nouchka/sqlite3
          command: ["/bin/sh", "-c"]
          args:
            - |
              if [ ! -f /data/focalboard.db ]; then
                sqlite3 /data/focalboard.db "VACUUM;";
              fi
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: focalboard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: FOCALBOARD_PORT
              value: "8000"
          volumeMounts:
            - mountPath: /opt/focalboard/data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: focalboard-pvc
