apiVersion: v1
kind: Service
metadata:
  name: focalboard
spec:
  type: {{ .Values.service.type }}
  selector:
    app: focalboard
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
